### ISSUE TITLE
LOG V1.0

### ISSUE THREAD

**Issue by dhstsw** [gaf1990/synthv-to-language-phoneme-plugin#1]
[Logger Thu Oct 24 11:18:23 2024] INFO  - OS: Windows
[Logger Thu Oct 24 11:18:24 2024] INFO  - Language: IT
[Logger Thu Oct 24 11:18:24 2024] INFO  - Start processing rules 
[Logger Thu Oct 24 11:18:24 2024] INFO  - Open IPA rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT.dic
[Logger Thu Oct 24 11:20:21 2024] INFO  - OS: Windows
[Logger Thu Oct 24 11:20:23 2024] INFO  - Language: IT
[Logger Thu Oct 24 11:20:23 2024] INFO  - Start processing rules 
[Logger Thu Oct 24 11:20:23 2024] INFO  - Open IPA rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT.dic
[Logger Thu Oct 24 11:20:23 2024] INFO  - Open dream rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT-dream.dic
[Logger Thu Oct 24 11:20:23 2024] INFO  - End processing rules 
[Logger Thu Oct 24 11:20:23 2024] INFO  - Start processing notes 
[Logger Thu Oct 24 11:20:23 2024] INFO  - Lyric come --> IPA: kome --> Dream: 1: {1: k o m e 2: CAN 3: kome } 
[Logger Thu Oct 24 11:20:23 2024] INFO  - Lyric mi --> IPA: mi --> Dream: 1: {1: m i 2: CAN 3: mi } 
[Logger Thu Oct 24 11:20:23 2024] INFO  - Lyric manchi --> IPA: maŋki --> Dream: 1: {1: m a 2: CAN 3: ma } 2: {1: N 2: SPA 3: ŋ } 3: {1: k i 2: CAN 3: ki } 
[Logger Thu Oct 24 11:20:23 2024] INFO  - Lyric tu --> IPA: tu --> Dream: 1: {1: t 2: SPA 3: t } 2: {1: u 2: CAN 3: u } 
[Logger Thu Oct 24 11:23:14 2024] INFO  - OS: Windows
[Logger Thu Oct 24 11:23:15 2024] INFO  - Language: IT
[Logger Thu Oct 24 11:23:15 2024] INFO  - Start processing rules 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Open IPA rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT.dic
[Logger Thu Oct 24 11:23:15 2024] INFO  - Open dream rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT-dream.dic
[Logger Thu Oct 24 11:23:15 2024] INFO  - End processing rules 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Start processing notes 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Lyric io --> IPA: jo --> Dream: 1: {1: j o 2: CAN 3: jo } 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Lyric non --> IPA: non --> Dream: 1: {1: n o n 2: CAN 3: non } 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Lyric so --> IPA: so --> Dream: 1: {1: s o 2: CAN 3: so } 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Lyric se --> IPA: se --> Dream: 1: {1: s e 2: CAN 3: se } 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Lyric il --> IPA: il --> Dream: 1: {1: i l 2: CAN 3: il } 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Lyric tuo --> IPA: tʊɔ --> Dream: 1: {1: t 2: SPA 3: t } 2: {1: u O 2: CAN 3: ʊɔ } 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Lyric Cannone --> IPA: Cannone --> Dream: 1: {1: C 3: C } 2: {1: a n n o n e 2: CAN 3: annone } 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Cannot find C in .dic file. Set JAP as default
[Logger Thu Oct 24 11:23:15 2024] INFO  - Lyric + --> IPA: + --> Dream: 1: {1: + 2: CAN 3: + } 
[Logger Thu Oct 24 11:23:15 2024] INFO  - Lyric + --> IPA: + --> Dream: 1: {1: + 2: CAN 3: + } 
[Logger Thu Oct 24 11:23:43 2024] INFO  - OS: Windows
[Logger Thu Oct 24 11:23:45 2024] INFO  - Language: IT
[Logger Thu Oct 24 11:23:45 2024] INFO  - Start processing rules 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Open IPA rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT.dic
[Logger Thu Oct 24 11:23:45 2024] INFO  - Open dream rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT-dream.dic
[Logger Thu Oct 24 11:23:45 2024] INFO  - End processing rules 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Start processing notes 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Lyric io --> IPA: jo --> Dream: 1: {1: j o 2: CAN 3: jo } 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Lyric non --> IPA: non --> Dream: 1: {1: n o n 2: CAN 3: non } 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Lyric so --> IPA: so --> Dream: 1: {1: s o 2: CAN 3: so } 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Lyric se --> IPA: se --> Dream: 1: {1: s e 2: CAN 3: se } 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Lyric il --> IPA: il --> Dream: 1: {1: i l 2: CAN 3: il } 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Lyric tuo --> IPA: tʊɔ --> Dream: 1: {1: t 2: SPA 3: t } 2: {1: u O 2: CAN 3: ʊɔ } 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Lyric Cannone --> IPA: Cannone --> Dream: 1: {1: C 3: C } 2: {1: a n n o n e 2: CAN 3: annone } 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Cannot find C in .dic file. Set JAP as default
[Logger Thu Oct 24 11:23:45 2024] INFO  - Lyric + --> IPA: + --> Dream: 1: {1: + 2: CAN 3: + } 
[Logger Thu Oct 24 11:23:45 2024] INFO  - Lyric + --> IPA: + --> Dream: 1: {1: + 2: CAN 3: + } 
[Logger Thu Oct 24 11:24:19 2024] INFO  - OS: Windows
[Logger Thu Oct 24 11:24:20 2024] INFO  - Language: IT
[Logger Thu Oct 24 11:24:20 2024] INFO  - Start processing rules 
[Logger Thu Oct 24 11:24:20 2024] INFO  - Open IPA rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT.dic
[Logger Thu Oct 24 11:24:20 2024] INFO  - Open dream rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT-dream.dic
[Logger Thu Oct 24 11:24:20 2024] INFO  - End processing rules 
[Logger Thu Oct 24 11:24:20 2024] INFO  - Start processing notes 
[Logger Thu Oct 24 11:24:20 2024] INFO  - Lyric tuo --> IPA: tʊɔ --> Dream: 1: {1: t 2: SPA 3: t } 2: {1: u O 2: CAN 3: ʊɔ } 
[Logger Thu Oct 24 11:28:45 2024] INFO  - OS: Windows
[Logger Thu Oct 24 11:28:47 2024] INFO  - Language: IT
[Logger Thu Oct 24 11:28:47 2024] INFO  - Start processing rules 
[Logger Thu Oct 24 11:28:47 2024] INFO  - Open IPA rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT.dic
[Logger Thu Oct 24 11:28:47 2024] INFO  - Open dream rule file C:\Users\dhs\Documenti\Dreamtonics\Synthesizer V Studio\scripts\Utilities\languages\IT-dream.dic
[Logger Thu Oct 24 11:28:47 2024] INFO  - End processing rules 
[Logger Thu Oct 24 11:28:47 2024] INFO  - Start processing notes 
[Logger Thu Oct 24 11:28:47 2024] INFO  - Lyric Cannone --> IPA: Cannone --> Dream: 1: {1: C 3: C } 2: {1: a n n o n e 2: CAN 3: annone } 
[Logger Thu Oct 24 11:28:47 2024] INFO  - Cannot find C in .dic file. Set JAP as default

**Comment by gaf1990** [comment]
Fixed in newer version.
In particular
- Add support for capital letter
- Add support for sillabation and "+" and "-"
